[package]
name = "my_bin"
version = "0.0.0"
edition = "2024"
publish = false

[[bin]]
name = "my_bin"
path = "src/bin/my_bin.rs"

[dependencies]
my_buildrs = { workspace = true }
proc-macro2 = { workspace = true }
thiserror = { workspace = true }
